REM Automatically generated from Makefile
..\..\..\bin\lcc   -debug -c -o obj\common.o src\common.c
..\..\..\bin\lcc   -debug -c -o obj\main.o src\main.c
..\..\..\bin\lcc   -debug -c -o obj\cast_tiles.o res\sprites\cast_tiles.c
..\..\..\bin\lcc   -debug -c -o obj\indoor_tiles.o res\maps\indoor_tiles.c
..\..\..\bin\lcc   -debug -c -o obj\home.o res\maps\home.c
..\..\..\bin\lcc   -debug -c -o obj\player.o src\player.c
..\..\..\bin\lcc   -debug -c -o obj\GameTitle.o src\GameTitle.c
..\..\..\bin\lcc   -debug -c -o obj\CoreGameLoop.o src\CoreGameLoop.c
..\..\..\bin\lcc   -debug -c -o obj\GameJohnDoe.o src\GameJohnDoe.c
..\..\..\bin\lcc   -debug -c -o obj\Globe_Tiles.o res\sprites\Globe_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Title_Map.o res\misc\Title_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Title_Tiles.o res\misc\Title_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\JohnDoe_Map.o res\misc\JohnDoe_Map.c
..\..\..\bin\lcc   -debug -c -o obj\JohnDoe_Tiles.o res\misc\JohnDoe_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Bestiary_Map.o res\misc\Bestiary_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Crow_Tiles.o res\enemies\Crow_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Crow_Map.o res\enemies\Crow_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Bestiary.o src\Bestiary.c
..\..\..\bin\lcc   -debug -c -o obj\Font.o res\misc\Font.c
..\..\..\bin\lcc   -debug -c -o obj\Wally_Tiles.o res\enemies\Wally_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Wally_Map.o res\enemies\Wally_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Gypsy_Tiles.o res\enemies\Gypsy_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Gypsy_Map.o res\enemies\Gypsy_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Skateboard_Tiles.o res\sprites\Skateboard_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Cop_Tiles.o res\enemies\Cop_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Officer_Map.o res\enemies\Officer_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Police_Map.o res\enemies\Police_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Sheriff_Map.o res\enemies\Sheriff_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Chief_Map.o res\enemies\Chief_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Tick_Tiles.o res\enemies\Tick_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Tick_Map.o res\enemies\Tick_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Man_Tiles.o res\enemies\Man_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Man_Map.o res\enemies\Man_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Sis_Tiles.o res\enemies\Sis_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\BigSis_Map.o res\enemies\BigSis_Map.c
..\..\..\bin\lcc   -debug -c -o obj\MadSis_Map.o res\enemies\MadSis_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Car_Tiles.o res\enemies\Car_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Car_Map.o res\enemies\Car_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Semi_Tiles.o res\enemies\Semi_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Semi_Map.o res\enemies\Semi_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Battle.o src\Battle.c
..\..\..\bin\lcc   -debug -c -o obj\Battle_Map.o res\misc\Battle_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Drunk_Tiles.o res\enemies\Drunk_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Drunk_Map.o res\enemies\Drunk_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Experiment_Tiles.o res\enemies\Experiment_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Experiment_Map.o res\enemies\Experiment_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Ghost_Map.o res\enemies\Ghost_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Ghost_Tiles.o res\enemies\Ghost_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Saucer_Tiles.o res\enemies\Saucer_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Saucer_Map.o res\enemies\Saucer_Map.c
..\..\..\bin\lcc   -debug -c -o obj\SockHead_Map.o res\enemies\SockHead_Map.c
..\..\..\bin\lcc   -debug -c -o obj\SockHead_Tiles.o res\enemies\SockHead_Tiles.c
..\..\..\bin\lcc   -debug -c -o obj\Toby_Map.o res\enemies\Toby_Map.c
..\..\..\bin\lcc   -debug -c -o obj\Toby_Tiles.o res\enemies\Toby_Tiles.c
..\..\..\bin\lcc   -Wl-yt0x1A -Wl-yo16 -Wl-ya16 -debug -o bin\Memory.gb obj\main.o obj\cast_tiles.o obj\indoor_tiles.o obj\home.o obj\player.o obj\GameTitle.o obj\GameTitle.o obj\Globe_Tiles.o obj\Title_Map.o obj\Title_Tiles.o obj\common.o obj\CoreGameLoop.o obj\JohnDoe_Map.o obj\JohnDoe_Tiles.o obj\GameJohnDoe.o obj\Bestiary_Map.o obj\Crow_Tiles.o obj\Crow_Map.o obj\Bestiary.o obj\Font.o obj\Gypsy_Tiles.o obj\Gypsy_Map.o obj\Wally_Tiles.o obj\Wally_Map.o obj\Skateboard_Tiles.o obj\Cop_Tiles.o obj\Officer_Map.o obj\Police_Map.o obj\Sheriff_Map.o obj\Chief_Map.o obj\Tick_Tiles.o obj\Tick_Map.o obj\Man_Tiles.o obj\Man_Map.o obj\Sis_Tiles.o obj\BigSis_Map.o obj\MadSis_Map.o obj\Car_Tiles.o obj\Car_Map.o obj\Semi_Tiles.o obj\Semi_Map.o obj\Battle.o obj\Battle_Map.o obj\Drunk_Tiles.o obj\Drunk_Map.o obj\Experiment_Tiles.o obj\Experiment_Map.o obj\Ghost_Map.o obj\Ghost_Tiles.o obj\Saucer_Tiles.o obj\Saucer_Map.o obj\SockHead_Map.o obj\SockHead_Tiles.o obj\Toby_Map.o obj\Toby_Tiles.o
