/*

 BIGSIS_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 7
   Tile set      : C:\gbtd22\Memory\BigSis.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BigSis_MapWidth 5
#define BigSis_MapHeight 7
#define BigSis_MapBank 0

const extern unsigned char BigSis_Map[];

/* End of BIGSIS_MAP.H */
