/*

 CROW_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 7
   Tile set      : C:\gbtd22\Memory\Crow.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Crow_MapWidth 5
#define Crow_MapHeight 7
#define Crow_MapBank 0

extern unsigned char Crow_Map[];

/* End of CROW_MAP.H */
