/*

 DRUNK_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 6
   Tile set      : C:\gbtd22\Memory\Drunk.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Drunk_MapWidth 4
#define Drunk_MapHeight 6
#define Drunk_MapBank 0

unsigned char Drunk_Map[] =
{
  0x81,0x87,0x8D,0x80,0x82,0x88,0x8E,0x93,0x83,0x89,
  0x8F,0x94,0x84,0x8A,0x90,0x95,0x85,0x8B,0x91,0x96,
  0x86,0x8C,0x92,0x97
};

/* End of DRUNK_MAP.C */
