/*

 GHOST_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : C:\gbtd22\Memory\Ghost.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Ghost_MapWidth 4
#define Ghost_MapHeight 5
#define Ghost_MapBank 0

unsigned char Ghost_Map[] =
{
  0x80,0x85,0x8A,0x80,0x81,0x86,0x8B,0x8F,0x82,0x87,
  0x8C,0x90,0x83,0x88,0x8D,0x91,0x84,0x89,0x8E,0x92
};

/* End of GHOST_MAP.C */
