/*

 GYPSY_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 7
   Tile set      : C:\gbtd22\Memory\Gypsy.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Gypsy_MapWidth 6
#define Gypsy_MapHeight 7
#define Gypsy_MapBank 0

extern unsigned char Gypsy_Map[];

/* End of GYPSY_MAP.H */
