/*

 HOME.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 37 x 62
   Tile set      : C:\gbtd22\Memory_Indoors.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define HomeWidth 37
#define HomeHeight 62
#define HomeBank 0

extern const unsigned char Home[];
extern const char HOME_COLLISION[][17];
/* End of HOME.H */
