/*

 HOME_LIVING_ROOM.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\gbtd22\Memory_Indoors.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapWidth 32
#define MapHeight 32
#define MapBank 0

extern const unsigned char LIVING_ROOM[];
extern char LIVING_ROOM_COLLISION[][17];

/* End of HOME_LIVING_ROOM.H */
