/*

 JOHNDOE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbtd22\Memory\JohnDoe.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define JohnDoe_MapWidth 20
#define JohnDoe_MapHeight 18
#define JohnDoe_MapBank 0

extern unsigned char JohnDoe_Map[];

/* End of JOHNDOE_MAP.H */
