/*

 MAN_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 6
   Tile set      : C:\gbtd22\Memory\Man.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Man_MapWidth 6
#define Man_MapHeight 6
#define Man_MapBank 0

extern unsigned char Man_Map[];

/* End of MAN_MAP.H */
