/*

 OFFICER_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 7
   Tile set      : C:\gbtd22\Memory\Cop.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Officer_MapWidth 6
#define Officer_MapHeight 7
#define Officer_MapBank 0

const extern unsigned char Officer_Map[];

/* End of OFFICER_MAP.H */
