/*

 PETS_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 36 x 32
   Tile set      : C:\gbtd22\Memory\Memory_Indoors.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Pets_MapWidth 36
#define Pets_MapHeight 32
#define Pets_MapBank 0

extern unsigned char Pets_Map[];

/* End of PETS_MAP.H */
