/*

 POLICE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 7
   Tile set      : C:\gbtd22\Memory\Cop.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Police_MapWidth 6
#define Police_MapHeight 7
#define Police_MapBank 0

const extern unsigned char Police_Map[];

/* End of POLICE_MAP.H */
