/*

 TOBY_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 7
   Tile set      : C:\gbtd22\Memory\Toby.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Toby_MapWidth 4
#define Toby_MapHeight 7
#define Toby_MapBank 0

unsigned char Toby_Map[] =
{
  0x81,0x88,0x8F,0x80,0x82,0x89,0x90,0x80,0x83,0x8A,
  0x91,0x80,0x84,0x8B,0x92,0x96,0x85,0x8C,0x93,0x97,
  0x86,0x8D,0x94,0x98,0x87,0x8E,0x95,0x99
};

/* End of TOBY_MAP.C */
