/*

 CAR_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 6 x 5
   Tile set      : C:\gbtd22\Memory\Car.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Car_MapWidth 6
#define Car_MapHeight 5
#define Car_MapBank 0

const extern unsigned char Car_Map[];

/* End of CAR_MAP.H */
