/*

 CAR_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 6 x 5
   Tile set      : C:\gbtd22\Memory\Car.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/
#pragma bank 5

#define Car_MapWidth 6
#define Car_MapHeight 5
#define Car_MapBank 0

const unsigned char Car_Map[] =
{
  0x9B,0x84,0x89,0x8E,0x9B,0x9B,0x80,0x85,0x8A,0x8F,
  0x93,0x97,0x81,0x86,0x8B,0x90,0x94,0x98,0x82,0x87,
  0x8C,0x91,0x95,0x99,0x83,0x88,0x8D,0x92,0x96,0x9A
};

/* End of CAR_MAP.C */
