/*

 CHIEF_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 6 x 7
   Tile set      : C:\gbtd22\Memory\Cop.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Chief_MapWidth 6
#define Chief_MapHeight 7
#define Chief_MapBank 0

const extern unsigned char Chief_Map[];

/* End of CHIEF_MAP.H */
