/*

 DRUNK_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255 (auto)
   Map size      : 4 x 6
   Tile set      : C:\gbtd22\Memory\Drunk.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Drunk_MapWidth 4
#define Drunk_MapHeight 6
#define Drunk_MapBank 0

const extern unsigned char Drunk_Map[];

/* End of DRUNK_MAP.H */
