/*

 GHOST_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 4 x 5
   Tile set      : C:\gbtd22\Memory\Ghost.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Ghost_MapWidth 4
#define Ghost_MapHeight 5
#define Ghost_MapBank 0

const extern unsigned char Ghost_Map[];

/* End of GHOST_MAP.H */
