/*

 MADSIS_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 5 x 7
   Tile set      : C:\gbtd22\Memory\BigSis.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MadSis_MapWidth 5
#define MadSis_MapHeight 7
#define MadSis_MapBank 0

const extern unsigned char MadSis_Map[];

/* End of MADSIS_MAP.H */
