/*

 SAUCER_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 5 x 3
   Tile set      : C:\gbtd22\Memory\Saucer.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Saucer_MapWidth 5
#define Saucer_MapHeight 3
#define Saucer_MapBank 0

const extern unsigned char Saucer_Map[];

/* End of SAUCER_MAP.H */
