/*

 SAUCER_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 5 x 3
   Tile set      : C:\gbtd22\Memory\Saucer.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/
#pragma bank 5
#define Saucer_MapWidth 5
#define Saucer_MapHeight 3
#define Saucer_MapBank 0

const unsigned char Saucer_Map[] =
{
  0x80,0x83,0x86,0x89,0x8C,0x81,0x84,0x87,0x8A,0x8D,
  0x82,0x85,0x88,0x8B,0x80
};

/* End of SAUCER_MAP.C */
