/*

 SEMI_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 6 x 8
   Tile set      : C:\gbtd22\Memory\Semi_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Semi_MapWidth 6
#define Semi_MapHeight 8
#define Semi_MapBank 0

const extern unsigned char Semi_Map[];

/* End of SEMI_MAP.H */
