/*

 SOCKHEAD_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 7
   Tile set      : C:\gbtd22\Memory\SockHead.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define SockHead_MapWidth 4
#define SockHead_MapHeight 7
#define SockHead_MapBank 0

const extern unsigned char SockHead_Map[];

/* End of SOCKHEAD_MAP.H */
