/*

 TICK_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 5 x 5
   Tile set      : C:\gbtd22\Memory\Tick.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Tick_MapWidth 5
#define Tick_MapHeight 5
#define Tick_MapBank 0

const extern unsigned char Tick_Map[];

/* End of TICK_MAP.H */
