/*

 TICK_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 5 x 5
   Tile set      : C:\gbtd22\Memory\Tick.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/
#pragma bank 5
#define Tick_MapWidth 5
#define Tick_MapHeight 5
#define Tick_MapBank 0

const unsigned char Tick_Map[] =
{
  0x80,0x83,0x88,0x8C,0x91,0x80,0x84,0x89,0x8D,0x91,
  0x81,0x85,0x8A,0x8E,0x92,0x82,0x86,0x8B,0x8F,0x93,
  0x94,0x87,0x94,0x90,0x94
};

/* End of TICK_MAP.C */
