/*

 TOBY_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255 (auto)
   Map size      : 4 x 7
   Tile set      : C:\gbtd22\Memory\Toby.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Toby_MapWidth 4
#define Toby_MapHeight 7
#define Toby_MapBank 0

const extern unsigned char Toby_Map[];

/* End of TOBY_MAP.H */
