/*

 WALLY_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 5 x 6
   Tile set      : C:\gbtd22\Memory\Wally.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/
#pragma bank 5
#define Wally_MapWidth 5
#define Wally_MapHeight 6
#define Wally_MapBank 0

const unsigned char Wally_Map[] =
{
  0x80,0x86,0x8C,0x92,0x97,0x81,0x87,0x8D,0x93,0x98,
  0x82,0x88,0x8E,0x94,0x99,0x83,0x89,0x8F,0x95,0x9A,
  0x84,0x8A,0x90,0x96,0x9B,0x85,0x8B,0x91,0x9C,0x9C
};

/* End of WALLY_MAP.C */
