/*

 WALLY_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 255
   Map size      : 5 x 6
   Tile set      : C:\gbtd22\Memory\Wally.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Wally_MapWidth 5
#define Wally_MapHeight 6
#define Wally_MapBank 0

const extern unsigned char Wally_Map[];

/* End of WALLY_MAP.H */
