/*

 BATTLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 23
   Tile set      : C:\gbtd22\Memory\Font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Battle_MapWidth 20
#define Battle_MapHeight 23
#define Battle_MapBank 0

extern const unsigned char Battle_Map[];

/* End of BATTLE.H */
