/*

 BESTIARY_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbtd22\Memory\Font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Bestiary_MapWidth 20
#define Bestiary_MapHeight 18
#define Bestiary_MapBank 0

extern const unsigned char Bestiary_Map[];

/* End of BESTIARY_MAP.H */
