/*

 TITLE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbtd22\Memory\Title.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Title_MapWidth 20
#define Title_MapHeight 18
#define Title_MapBank 0

const extern unsigned char Title_Map[];

/* End of TITLE_MAP.H */
