#include <gb/gb.h>
#include <stdint.h>
#include <stdio.h>
#include "../res/cast_tiles.h"
#include "../res/indoor_tiles.h"
#include "../res/Pets_Map.h"
#include "../src/player.h"
#include "../src/common.h"
#include "../res/Skateboard_Tiles.h"